[package]
name = "lildb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
rustyline = "12.0.0"
yansi = "0.5.1"
